name: authentication_repository
description: An authentication interface implemented with firebase authentication service.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.24.2

dependencies:
  crypto: ^3.0.2
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.1.0
