#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/yanrodriguez/fvm/versions/3.22.0"
export "FLUTTER_APPLICATION_PATH=/Users/yanrodriguez/Documents/work/Blueprint/blueprint"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/yanrodriguez/Documents/work/Blueprint/blueprint/lib/main_development.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=RkxVVFRFUl9BUFBfRkxBVk9SPWRldmVsb3BtZW50"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/yanrodriguez/Documents/work/Blueprint/blueprint/.dart_tool/package_config.json"
export "FLAVOR=development"
