// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0bXPkorTuzBGA31DhMqHO9Z4sHa0wfxc',
    appId: '1:333437725100:web:05b8f6b9fc3512d9b03209',
    messagingSenderId: '333437725100',
    projectId: 'polletask-dev',
    authDomain: 'polletask-dev.firebaseapp.com',
    databaseURL: 'https://polletask-dev-default-rtdb.firebaseio.com',
    storageBucket: 'polletask-dev.appspot.com',
    measurementId: 'G-R0T08VBP98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEicy3hfG1T9v_wBK_PudTRML-OjhAL9s',
    appId: '1:333437725100:android:baadcafcea63d0e0b03209',
    messagingSenderId: '333437725100',
    projectId: 'polletask-dev',
    databaseURL: 'https://polletask-dev-default-rtdb.firebaseio.com',
    storageBucket: 'polletask-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMkEuCELz3ERI8Qih2epyjmDnzCuxv4dw',
    appId: '1:333437725100:ios:a38b07f6d3bafbffb03209',
    messagingSenderId: '333437725100',
    projectId: 'polletask-dev',
    databaseURL: 'https://polletask-dev-default-rtdb.firebaseio.com',
    storageBucket: 'polletask-dev.appspot.com',
    iosClientId:
        '333437725100-gedi3r0oh08vad1f3c6elp4ep8j2vjg6.apps.googleusercontent.com',
    iosBundleId: 'com.yarn.blueprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMkEuCELz3ERI8Qih2epyjmDnzCuxv4dw',
    appId: '1:333437725100:ios:8e1085afcbafb89ab03209',
    messagingSenderId: '333437725100',
    projectId: 'polletask-dev',
    databaseURL: 'https://polletask-dev-default-rtdb.firebaseio.com',
    storageBucket: 'polletask-dev.appspot.com',
    iosClientId:
        '333437725100-3vjf64sklpsbblachkvtunl58scftn03.apps.googleusercontent.com',
    iosBundleId: 'com.yarn.blueprint.blueprint.RunnerTests',
  );
}
