// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prd.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClUZgTJOQEmA12yemDWc80mMhj6vP4qmk',
    appId: '1:364868056134:web:65afe23880e082d7540647',
    messagingSenderId: '364868056134',
    projectId: 'blueprint-384623',
    authDomain: 'blueprint-384623.firebaseapp.com',
    storageBucket: 'blueprint-384623.appspot.com',
    measurementId: 'G-C9HPJRBR3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUm-532WpmXJSA_PKZSl-Ao3r9rk6PLyU',
    appId: '1:364868056134:android:6a5405fb7628d00a540647',
    messagingSenderId: '364868056134',
    projectId: 'blueprint-384623',
    storageBucket: 'blueprint-384623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvHsZWn2WJTmSf2V_7sCF7JohT4_5dj8',
    appId: '1:364868056134:ios:fc9480d8979338e8540647',
    messagingSenderId: '364868056134',
    projectId: 'blueprint-384623',
    storageBucket: 'blueprint-384623.appspot.com',
    iosClientId:
        '364868056134-mmcaj71vch2qa827319srbi020anl24p.apps.googleusercontent.com',
    iosBundleId: 'com.blueprint.app.prd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwvHsZWn2WJTmSf2V_7sCF7JohT4_5dj8',
    appId: '1:364868056134:ios:8e9558a33d6cf587540647',
    messagingSenderId: '364868056134',
    projectId: 'blueprint-384623',
    storageBucket: 'blueprint-384623.appspot.com',
    iosBundleId: 'com.yarn.blueprint.RunnerTests',
  );
}
