// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmtNwZJcrLvJ-pTQH7a09wdfVOPCc_G1o',
    appId: '1:960695221560:web:eab0f0d42665a914edd5cd',
    messagingSenderId: '960695221560',
    projectId: 'blueprint-stg',
    authDomain: 'blueprint-stg.firebaseapp.com',
    storageBucket: 'blueprint-stg.appspot.com',
    measurementId: 'G-CZDMJH17Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlMPe7s5v4mLzqFopEqUxqezhBbc3-YNc',
    appId: '1:960695221560:android:1b9d1516d3ef644dedd5cd',
    messagingSenderId: '960695221560',
    projectId: 'blueprint-stg',
    storageBucket: 'blueprint-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDka1DYkHemByTlNa-CBh9c5Lldjc8ScMc',
    appId: '1:960695221560:ios:eb578c36265e6efcedd5cd',
    messagingSenderId: '960695221560',
    projectId: 'blueprint-stg',
    storageBucket: 'blueprint-stg.appspot.com',
    iosClientId:
        '960695221560-j7cj8kdo1itsk9tpa38agkgh8hg7n90h.apps.googleusercontent.com',
    iosBundleId: 'com.blueprint.app.stg',
  );
}
