name: ci-prd

permissions: write-all

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
  build_and_deploy:
    uses: ./.github/workflows/firebase-hosting-preview.yml
    with:
      project_id: blueprint-384623
      target: lib/main_production.dart
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRD }}
      OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY_PRD }}
